apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 968641182612.dkr.ecr.eu-north-1.amazonaws.com/edugen-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        # Health Probes
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 5
        # Resource Management
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        # Environment Variables from Secrets
        env:
        - name: LLM_API_KEY
          valueFrom:
            secretKeyRef:
              name: edugen-secrets
              key: GEMINI_API_KEY
        - name: IMAGE_API_KEY
          valueFrom:
            secretKeyRef:
              name: edugen-secrets
              key: IMAGE_API_KEY
        - name: LLM_MODEL
          value: "gemini-3-flash-preview"
        - name: LLM_BASE_URL
          value: "https://generativelanguage.googleapis.com/v1beta"
        - name: IMAGE_MODEL
          value: "img4"
        - name: IMAGE_BASE_URL
          value: "https://api.infip.pro/v1"
        - name: LOG_LEVEL
          value: "INFO"
