apiVersion: v1
kind: Secret
metadata:
  name: edugen-secrets
type: Opaque
data:
  # Values must be base64 encoded. 
  # Example: echo -n "your-key" | base64
  # Default placeholders below are for documentation purposes.
  GEMINI_API_KEY: LkFiOFJONktPeE8wWnpTU1pYcnhod05zLWdSakNBT1hWWGo4MV90VmFkSl93RnBDU0VR
  IMAGE_API_KEY: aW5maXAtM2Q2OGEyMGU=
